import type { Metadata } from "next";
import { Plus } from "lucide-react";
import { FuelForm } from "@/components/forms/fuel-form";
import { PageHeader } from "@/components/layout/page-header";
import { Panel } from "@/components/layout/panel";
import { VehiclePicker } from "@/components/layout/vehicle-picker";
import { SourceBadge } from "@/components/ui/source-badge";
import { TrendChart } from "@/components/dashboard/trend-chart";
import { requirePageUser } from "@/lib/auth";
import { fuelStats, monthKey, monthKeys } from "@/lib/analytics";
import { vehicleWorkspace } from "@/lib/vehicle-workspace";
import { formatCurrency, formatDate, formatNumber } from "@/lib/format";
export const metadata: Metadata = { title: "Carburant" };
const metric = (value: number | null, unit: string) => value === null ? "—" : formatNumber(value, unit);
export default async function FuelPage({ searchParams }: { searchParams: Promise<{ vehicle?: string }> }) {
  const user = await requirePageUser(), query = await searchParams;
  const { vehicles, vehicle } = await vehicleWorkspace(user.id, query.vehicle);
  const entries = vehicle?.fuelEntries ?? [], now = new Date(), stats = fuelStats(entries, now);
  const rows = entries.toReversed().slice(0, 100);
  const metrics = [["Ce mois", formatCurrency(stats.month)], ["Mois précédent", formatCurrency(stats.previous)], ["Évolution", stats.change === null ? "—" : `${stats.change >= 0 ? "+" : ""}${formatNumber(stats.change, " %")}`], ["Consommation fiable", metric(stats.consumption, " L/100 km")], ["Coût total", formatCurrency(stats.total)], ["Prix moyen / litre", stats.unitPrice === null ? "—" : formatCurrency(stats.unitPrice)], ["Coût / 100 km", stats.costPer100 === null ? "—" : formatCurrency(stats.costPer100)], ["Distance moyenne", metric(stats.averageDistance, " km")], ["Distance minimale", metric(stats.minimumDistance, " km")], ["Distance maximale", metric(stats.maximumDistance, " km")], ["Moyenne des 5 derniers intervalles", metric(stats.rollingDistance, " km")]];
  return <div className="space-y-7"><PageHeader title="Carburant" description="Budget, distances entre passages à la pompe et consommation fiable, par véhicule." /><VehiclePicker vehicles={vehicles} selected={vehicle?.id} href="/carburant" />
    {!vehicle ? <p className="text-sm text-[var(--muted)]">Ajoutez ou sélectionnez un véhicule dans le Garage.</p> : <>
    <section className="grid grid-cols-2 divide-y divide-[var(--line-soft)] rounded-xl bg-[var(--surface)] sm:grid-cols-2 xl:grid-cols-3">{metrics.map(([label, value]) => <div key={label} className="min-w-0 p-4 sm:p-5"><p className="text-xs sm:text-sm text-[var(--muted)]">{label}</p><p className="mt-3 text-xl sm:text-2xl font-medium tracking-[-0.03em]">{value}</p><SourceBadge kind="calculated" className="mt-3" /></div>)}</section>
    <p className="text-xs leading-5 text-[var(--muted)]">La moyenne fiable est pondérée par les distances entre pleins complets et inclut les appoints intermédiaires. Les intervalles incohérents sont exclus. Sans budget positif le mois précédent, le pourcentage est indisponible. Le mois en cours est incomplet.</p>
    <div className="grid gap-7 xl:grid-cols-2"><Panel title="Budget carburant mensuel" description="Les 12 derniers mois, d’après les montants enregistrés."><div className="p-5"><TrendChart data={monthKeys(now).map(key => ({ label: `${key.slice(5)}/${key.slice(2, 4)}`, value: entries.filter(e => monthKey(e.date) === key && e.date <= now).reduce((sum, e) => sum + Number(e.totalPrice), 0) }))} label="Budget carburant" unit="€" /></div></Panel><Panel title="Distance entre deux pleins" description="Les 12 derniers intervalles ; une baisse du compteur rend l’intervalle indisponible."><div className="p-5"><TrendChart data={stats.intervals.slice(-12).map(e => ({ label: `${e.date.getUTCDate()}/${e.date.getUTCMonth() + 1}`, value: e.distance }))} label="Distance entre pleins" unit="km" /></div></Panel></div>
    {vehicle.status === "ACTIVE" ? <details className="rounded-xl bg-[var(--surface)]"><summary className="flex cursor-pointer list-none items-center gap-3 px-5 py-4 text-sm font-medium"><Plus className="size-4 text-[var(--accent)]" />Enregistrer un plein</summary><div className="border-t border-[var(--line-soft)] p-5"><FuelForm vehicles={[vehicle]} /><p className="mt-4 text-xs text-[var(--muted)]">Un relevé kilométrique est créé à la même date, sauf s’il existe déjà.</p></div></details> : null}
    <Panel title="Registre des pleins" description={`${entries.length} pleins au total · les 100 derniers affichés`}><div className="overflow-x-auto"><table className="w-full min-w-[840px] text-left text-sm"><thead><tr className="border-b border-[var(--line-soft)] text-xs text-[var(--quiet)]">{["Date", "Compteur", "Volume", "Prix", "Prix/L", "Distance", "Consommation", "Coût/100 km"].map((title, i) => <th key={title} className={`px-5 py-3 font-medium ${i ? "text-right" : ""}`}>{title}</th>)}</tr></thead><tbody className="divide-y divide-[var(--line-soft)]">{rows.map(entry => { const interval = stats.intervals.find(i => i.date.getTime() === entry.date.getTime() && i.vehicleId === entry.vehicleId); return <tr key={entry.id}><td className="px-5 py-4 text-[var(--muted)]">{formatDate(entry.date)}{!entry.isFull ? <span className="mt-1 block text-xs text-[var(--quiet)]">Appoint partiel</span> : null}</td><td className="px-5 py-4 text-right">{formatNumber(entry.mileage, " km")}</td><td className="px-5 py-4 text-right">{formatNumber(Number(entry.liters), " L")}</td><td className="px-5 py-4 text-right">{formatCurrency(Number(entry.totalPrice))}</td><td className="px-5 py-4 text-right text-[var(--muted)]">{formatCurrency(Number(entry.unitPrice))}</td><td className="px-5 py-4 text-right">{metric(interval?.distance ?? null, " km")}</td><td className="px-5 py-4 text-right">{interval?.consumption != null ? metric(interval.consumption, " L/100 km") : "Non fiable"}</td><td className="px-5 py-4 text-right">{interval?.costPer100 != null ? formatCurrency(interval.costPer100) : "—"}</td></tr>; })}</tbody></table>{!entries.length ? <p className="px-5 py-10 text-sm text-[var(--muted)]">Enregistrez un premier plein pour ouvrir le suivi carburant de ce véhicule.</p> : null}</div></Panel></>}
  </div>;
}
