import Link from "next/link";
import { PageHeader } from "@/components/layout/page-header";
import { Panel } from "@/components/layout/panel";
import { VehiclePicker } from "@/components/layout/vehicle-picker";
import { SourceBadge } from "@/components/ui/source-badge";
import { TrendChart } from "@/components/dashboard/trend-chart";
import { Button } from "@/components/ui/button";
import { Select } from "@/components/ui/select";
import { requirePageUser } from "@/lib/auth";
import { annualStats, operatingCosts, ownershipStats, percentChange, monthKeys, monthKey, yearOf } from "@/lib/analytics";
import { vehicleWorkspace } from "@/lib/vehicle-workspace";
import { formatCurrency, formatNumber } from "@/lib/format";
export const metadata = { title: "Statistiques" };
const amount = (value: number | null) => value == null ? "—" : formatCurrency(value);
const number = (value: number | null, unit = "") => value == null ? "—" : formatNumber(value, unit);
export default async function StatisticsPage({ searchParams }: { searchParams: Promise<{ vehicle?: string; year?: string; compare?: string }> }) {
  const user = await requirePageUser(), query = await searchParams;
  const { vehicles, vehicle } = await vehicleWorkspace(user.id, query.vehicle);
  if (!vehicle) return <div className="space-y-6"><PageHeader title="Statistiques" description="Choisissez un véhicule pour analyser son coût." /><VehiclePicker vehicles={vehicles} href="/statistiques" /><Link href="/garage" className="text-[var(--accent)]">Ouvrir le garage</Link></div>;
  const now = new Date(), current = vehicle.finalMileage ?? vehicle.mileageReadings.at(-1)?.mileage ?? vehicle.purchaseMileage;
  const costs = operatingCosts(vehicle.expenses, vehicle.fuelEntries, vehicle.maintenance, vehicle.insurancePolicies, now, vehicle.saleDate);
  const ownership = ownershipStats(vehicle, current, costs, now);
  const first = Math.min(yearOf(vehicle.purchaseDate), ...costs.map(c => yearOf(c.date)), ...vehicle.mileageReadings.map(r => yearOf(r.date)));
  const years = Array.from({ length: Math.max(1, yearOf(now) - first + 1) }, (_, i) => yearOf(now) - i);
  const year = years.includes(Number(query.year)) ? Number(query.year) : years[0];
  const compare = years.includes(Number(query.compare)) ? Number(query.compare) : (years.find(y => y !== year) ?? year);
  const readings = [{ mileage: vehicle.purchaseMileage, date: vehicle.purchaseDate }, ...vehicle.mileageReadings];
  const selected = annualStats(year, readings, vehicle.fuelEntries, costs, now), baseline = annualStats(compare, readings, vehicle.fuelEntries, costs, now);
  const rows: [string, number | null, number | null, (n: number | null) => string][] = [
    ["Kilomètres observés", selected.distance, baseline.distance, n => number(n, " km")], ["Carburant acheté", selected.liters, baseline.liters, n => number(n, " L")], ["Dépenses carburant", selected.fuel, baseline.fuel, amount], ["Entretiens, réparations et pneus", selected.maintenance, baseline.maintenance, amount], ["Assurance", selected.insurance, baseline.insurance, amount], ["Autres dépenses", selected.other, baseline.other, amount], ["Total d’utilisation", selected.total, baseline.total, amount], ["Coût d’utilisation / km", selected.costPerKm, baseline.costPerKm, amount], ["Consommation moyenne fiable", selected.consumption, baseline.consumption, n => number(n, " L/100 km")],
  ];
  return <div className="space-y-7"><PageHeader title="Statistiques" description="Le coût de possession et les dépenses annuelles, véhicule par véhicule." /><VehiclePicker vehicles={vehicles} selected={vehicle.id} href="/statistiques" />
    <Panel title="Coût total de possession" description="Prix d’achat + carburant + entretien + assurance + autres dépenses − revente."><div className="grid grid-cols-2 divide-y divide-[var(--line-soft)] sm:grid-cols-2 xl:grid-cols-4">{[["Coût total", amount(ownership.total)], ["Moyenne mensuelle", amount(ownership.averageMonthly)], ["Moyenne annuelle", amount(ownership.averageAnnual)], ["Coût / km", amount(ownership.costPerKm)]].map(([label, value]) => <div key={label} className="min-w-0 p-4 sm:p-5"><p className="text-xs sm:text-sm text-[var(--muted)]">{label}</p><p className="mt-3 text-xl sm:text-2xl font-medium">{value}</p><SourceBadge kind="calculated" className="mt-3" /></div>)}</div><div className="grid gap-3 border-t border-[var(--line)] p-5 text-sm sm:grid-cols-2 xl:grid-cols-4">{[["Carburant", ownership.fuel], ["Entretien", ownership.maintenance], ["Assurance", ownership.insurance], ["Autres", ownership.other]].map(([label, value]) => <div key={String(label)} className="flex justify-between gap-3"><span className="text-[var(--muted)]">{label}</span><span>{formatCurrency(Number(value))}</span></div>)}</div><p className="border-t border-[var(--line-soft)] px-5 py-4 text-xs leading-5 text-[var(--muted)]">{ownership.incomplete ? "Prix d’achat absent : le total est incomplet. " : ""}{ownership.calculatedInsurance ? "L’assurance inclut des échéances calculées depuis les contrats. " : ""}Les moyennes répartissent le total sur la durée de possession, avec un minimum d’un mois. Le coût par km est indisponible sans distance positive.</p></Panel>
    <Panel title="Dépenses des 12 derniers mois" description="Montants saisis et échéances d’assurance calculées."><div className="p-5"><TrendChart data={monthKeys(now).map(key => ({ label: key.slice(5) + "/" + key.slice(2, 4), value: costs.filter(c => monthKey(c.date) === key).reduce((sum, c) => sum + Number(c.amount), 0) }))} unit="€" label="Coût mensuel" /></div></Panel>
    <Panel title="Comparaison annuelle"><form className="flex flex-wrap items-end gap-4 border-b border-[var(--line-soft)] p-5"><input type="hidden" name="vehicle" value={vehicle.id} /><div><label htmlFor="stats-year" className="mb-2 block text-xs text-[var(--muted)]">Année</label><Select id="stats-year" name="year" defaultValue={year}>{years.map(y => <option key={y}>{y}</option>)}</Select></div><div><label htmlFor="stats-compare" className="mb-2 block text-xs text-[var(--muted)]">Comparer avec</label><Select id="stats-compare" name="compare" defaultValue={compare}>{years.map(y => <option key={y}>{y}</option>)}</Select></div><Button type="submit">Comparer</Button></form><div className="overflow-x-auto"><table className="w-full min-w-[580px] text-left text-sm"><caption className="px-5 py-4 text-left text-xs leading-5 text-[var(--muted)]">Coûts d’utilisation hors achat et revente. Les distances sont attribuées à la date du dernier relevé de chaque intervalle ; les années incomplètes sont comparées telles quelles. <SourceBadge kind="calculated" /></caption><thead><tr className="border-b border-[var(--line)] text-[var(--muted)]"><th className="px-5 py-3 font-medium">Indicateur</th><th className="px-5 py-3 text-right font-medium">{year}{year === yearOf(now) ? " · en cours" : ""}</th><th className="px-5 py-3 text-right font-medium">{compare}{compare === yearOf(now) ? " · en cours" : ""}</th><th className="px-5 py-3 text-right font-medium">Évolution</th></tr></thead><tbody className="divide-y divide-[var(--line-soft)]">{rows.map(([label, value, prior, formatter]) => { const change = value != null && prior != null && year !== compare ? percentChange(value, prior) : null; return <tr key={label}><th className="px-5 py-4 font-normal">{label}</th><td className="px-5 py-4 text-right">{formatter(value)}</td><td className="px-5 py-4 text-right text-[var(--muted)]">{formatter(prior)}</td><td className="px-5 py-4 text-right">{change == null ? "—" : `${change >= 0 ? "+" : ""}${formatNumber(change, " %")}`}</td></tr>; })}</tbody></table></div></Panel>
  </div>;
}
