import Link from "next/link";
import { PageHeader } from "@/components/layout/page-header";
import { Panel } from "@/components/layout/panel";
import { VehiclePicker } from "@/components/layout/vehicle-picker";
import { RecordForm, type RecordValues } from "@/components/forms/record-form";
import { ApiActionButton } from "@/components/forms/api-action-button";
import { SourceBadge } from "@/components/ui/source-badge";
import { requirePageUser } from "@/lib/auth";
import { warrantyState, tireDistance } from "@/lib/analytics";
import { vehicleAlerts } from "@/lib/alerts";
import { vehicleWorkspace } from "@/lib/vehicle-workspace";
import { formatCurrency, formatDate, formatNumber } from "@/lib/format";
export const metadata = { title: "Suivi véhicule" };
function values(record: object): RecordValues {
  return Object.fromEntries(Object.entries(record).filter(([, v]) => !(Array.isArray(v))).map(([k, v]) => [k, v instanceof Date ? v.toISOString().slice(0, 10) : v == null || typeof v === "boolean" || typeof v === "number" || typeof v === "string" ? v : String(v)]));
}
const warrantyLabels = { ACTIVE: "Active", SOON: "Expire bientôt", EXPIRED: "Expirée", UPCOMING: "À venir" };
const typeLabels: Record<string, string> = { CONSTRUCTEUR: "Constructeur", EXTENSION: "Extension", OCCASION: "Occasion", AUTRE: "Autre", FAVORABLE: "Favorable", DEFAVORABLE: "Défavorable", CRITIQUE: "Défaillance critique", ETE: "Été", HIVER: "Hiver", QUATRE_SAISONS: "4 saisons", AVANT: "Avant", ARRIERE: "Arrière", COMPLET: "Complet" };
export default async function TrackingPage({ searchParams }: { searchParams: Promise<{ vehicle?: string }> }) {
  const user = await requirePageUser(), query = await searchParams;
  const { vehicles, vehicle } = await vehicleWorkspace(user.id, query.vehicle);
  if (!vehicle) return <div className="space-y-6"><PageHeader title="Suivi véhicule" description="Choisissez ou ajoutez un véhicule pour suivre ses contrats et équipements." /><VehiclePicker vehicles={vehicles} href="/suivi" /><Link href="/garage" className="text-[var(--accent)]">Ouvrir le garage</Link></div>;
  const current = vehicle.finalMileage ?? vehicle.mileageReadings.at(-1)?.mileage ?? vehicle.purchaseMileage, now = new Date();
  const alerts = vehicleAlerts(vehicle, now);
  return <div className="space-y-7"><PageHeader title="Suivi véhicule" description="Garanties, contrôle technique, assurance et pneumatiques." /><VehiclePicker vehicles={vehicles} selected={vehicle.id} href="/suivi" />
    <nav aria-label="Sections du suivi" className="flex flex-wrap gap-x-5 gap-y-2 border-b border-[var(--line)] pb-4 text-sm text-[var(--muted)]">{[["garanties", "Garanties"], ["controles", "Contrôle technique"], ["assurance", "Assurance"], ["pneus", "Pneumatiques"]].map(([id, label]) => <a key={id} href={`#${id}`} className="hover:text-[var(--accent)]">{label}</a>)}<Link href={`/documents?vehicle=${vehicle.id}`}>Documents</Link></nav>
    {alerts.length ? <Panel title="À surveiller"><div className="divide-y divide-[var(--line-soft)] px-5">{alerts.map(a => <div key={a.key} className="py-3 text-sm"><p className={a.urgent ? "text-[var(--danger)]" : "text-[var(--warning)]"}>{a.title}</p><p className="mt-1 text-[var(--muted)]">{a.detail}</p></div>)}</div></Panel> : null}
    <section id="garanties" className="scroll-mt-6"><Panel title="Garanties" description="Le premier seuil atteint, date ou kilométrage, termine la garantie."><div className="divide-y divide-[var(--line-soft)] px-5 sm:px-6">{vehicle.warranties.map(w => { const s = warrantyState(w, current, now); return <article key={w.id} className="py-5"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="font-medium">{w.title} · {typeLabels[w.type]}</h3><span className={s.status === "EXPIRED" ? "text-sm text-[var(--danger)]" : s.status === "SOON" ? "text-sm text-[var(--warning)]" : "text-sm text-[var(--accent)]"}>{warrantyLabels[s.status]}</span></div><p className="mt-2 text-sm text-[var(--muted)]">{formatDate(w.startDate)} — {formatDate(w.endDate)}{w.maxMileage !== null ? ` · ${formatNumber(w.maxMileage, " km maximum")}` : ""}</p>{["ACTIVE", "SOON"].includes(s.status) ? <p className="mt-2 text-sm">Encore {s.days} jours{s.km !== null ? ` ou ${formatNumber(s.km, " km")}` : ""} <SourceBadge kind="calculated" /></p> : null}{w.notes ? <p className="mt-2 text-sm text-[var(--muted)]">{w.notes}</p> : null}<Editor kind="warranty" vehicleId={vehicle.id} record={w} /></article>; })}{!vehicle.warranties.length ? <Empty text="Ajoutez une garantie pour suivre sa durée et son plafond kilométrique." /> : null}<Add kind="warranty" vehicleId={vehicle.id} label="Ajouter une garantie" /></div></Panel></section>
    <section id="controles" className="scroll-mt-6"><Panel title="Contrôle technique"><div className="divide-y divide-[var(--line-soft)] px-5 sm:px-6">{vehicle.inspections.map(i => <article key={i.id} className="py-5"><h3 className="font-medium">{formatDate(i.date)} · {typeLabels[i.result]}</h3><p className="mt-2 text-sm text-[var(--muted)]">Prochain contrôle : {formatDate(i.nextDate)}</p>{i.requiresFollowUp ? <p className="mt-2 text-sm text-[var(--warning)]">Contre-visite avant le {i.followUpDeadline ? formatDate(i.followUpDeadline) : "—"}</p> : null}{i.notes ? <p className="mt-2 text-sm text-[var(--muted)]">{i.notes}</p> : null}<Editor kind="inspection" vehicleId={vehicle.id} record={i} /></article>)}{!vehicle.inspections.length ? <Empty text="Enregistrez un contrôle et sa prochaine échéance. La contre-visite est suivie séparément." /> : null}<Add kind="inspection" vehicleId={vehicle.id} label="Ajouter un contrôle" /></div></Panel></section>
    <section id="assurance" className="scroll-mt-6"><Panel title="Assurance"><div className="divide-y divide-[var(--line-soft)] px-5 sm:px-6">{vehicle.insurancePolicies.map(p => <article key={p.id} className="py-5"><div className="flex flex-wrap justify-between gap-3"><h3 className="font-medium">{p.company}</h3><span className="text-sm">{p.cost == null ? "Coût non renseigné" : `${formatCurrency(Number(p.cost))} / ${p.frequency === "ANNUAL" ? "an" : "mois"}`}</span></div><p className="mt-2 text-sm text-[var(--muted)]">{p.contractReference ? `Contrat ${p.contractReference} · ` : ""}{formatDate(p.startDate)} — renouvellement le {formatDate(p.renewalDate)}</p><p className="mt-2 text-xs text-[var(--quiet)]">{p.includeInCosts ? "Échéances intégrées aux dépenses calculées" : "Information uniquement, hors dépenses automatiques"}</p>{p.notes ? <p className="mt-2 text-sm text-[var(--muted)]">{p.notes}</p> : null}<Editor kind="insurance" vehicleId={vehicle.id} record={p} /></article>)}{!vehicle.insurancePolicies.length ? <Empty text="Ajoutez votre contrat et choisissez si son coût doit entrer dans les statistiques." /> : null}<Add kind="insurance" vehicleId={vehicle.id} label="Ajouter un contrat" /></div></Panel></section>
    <section id="pneus" className="scroll-mt-6"><Panel title="Pneumatiques" description="L’historique conserve les montages et démontages de chaque train."><div className="divide-y divide-[var(--line-soft)] px-5 sm:px-6">{vehicle.tireSets.map(t => <article key={t.id} className="py-5"><div className="flex flex-wrap justify-between gap-3"><h3 className="font-medium">{t.brand}{t.model ? ` ${t.model}` : ""}</h3><span className="text-sm">{formatNumber(tireDistance(t, current), " km parcourus")} <SourceBadge kind="calculated" /></span></div><p className="mt-2 text-sm text-[var(--muted)]">{t.dimensions} · {typeLabels[t.type]} · {typeLabels[t.position]}</p><p className="mt-2 text-sm text-[var(--muted)]">Montés le {formatDate(t.mountedAt)} à {formatNumber(t.mountedMileage, " km")}{t.removedAt ? ` · démontés le ${formatDate(t.removedAt)} à ${formatNumber(t.removedMileage!, " km")}` : " · En service"}</p>{t.notes ? <p className="mt-2 text-sm text-[var(--muted)]">{t.notes}</p> : null}<Editor kind="tires" vehicleId={vehicle.id} record={t} /></article>)}{!vehicle.tireSets.length ? <Empty text="Ajoutez un montage. La distance parcourue sera calculée depuis le compteur actuel." /> : null}<Add kind="tires" vehicleId={vehicle.id} label="Ajouter un montage" /></div></Panel></section>
    <p className="text-sm text-[var(--muted)]">Plaquettes, disques, batterie et autres consommables se suivent dans <Link href="/entretiens" className="text-[var(--accent)]">Entretiens</Link>, avec un remplacement et une échéance.</p>
  </div>;
}
function Empty({ text }: { text: string }) { return <p className="py-6 text-sm leading-6 text-[var(--muted)]">{text}</p>; }
function Add({ kind, vehicleId, label }: { kind: "warranty" | "inspection" | "insurance" | "tires"; vehicleId: string; label: string }) { return <details className="py-4"><summary className="cursor-pointer py-1 text-sm font-medium text-[var(--accent)]">{label}</summary><div className="pt-5"><RecordForm kind={kind} vehicleId={vehicleId} /></div></details>; }
function Editor({ kind, vehicleId, record }: { kind: "warranty" | "inspection" | "insurance" | "tires"; vehicleId: string; record: { id: string } }) { return <details className="mt-4"><summary className="cursor-pointer py-1 text-xs text-[var(--accent)]">Modifier ou supprimer</summary><div className="space-y-5 pt-4"><RecordForm kind={kind} vehicleId={vehicleId} id={record.id} initial={values(record)} /><ApiActionButton endpoint={`/api/vehicle-records/${kind}/${record.id}`} method="DELETE" variant="danger" confirmation="Supprimer cet élément et recalculer les indicateurs associés ?">Supprimer</ApiActionButton></div></details>; }
